### ISSUE TITLE
Consider changing repo name

### ISSUE THREAD

**Issue by mikejohnson51** [JiwonBaik96/JiwonBaik96.github.io#1]
Hi Jiwon, 

Consider changing the repo name to "JiwonBaik96.github.io" to deploy it as a user web page. 

the readme is very helpful 👍 

Mike

**Comment by JiwonBaik96** [comment]
Hi Mike,
Thanks for the feedback.

I'll do it :)
Have a great day.

All the best,
Jiwon Baik
